name: Organize LeetCode files

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Move LeetCode files
        run: |
          mkdir -p LeetCode
          find . -maxdepth 1 -type f -name "leetcode*" -exec mv {} LeetCode/ \;

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-move LeetCode files to /LeetCode" || echo "No changes"
          git push
