name: Organize LeetCode problems

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Move LeetCode problem folders
        run: |
          mkdir -p LeetCode
          for dir in [0-9][0-9][0-9][0-9]-*; do
            if [ -d "$dir" ]; then
              echo "Moving $dir -> LeetCode/$dir"
              # 먼저 이동 시도, 실패하면 기존 폴더 지우고 다시 이동
              mv "$dir" LeetCode/ 2>/dev/null || (rm -rf "LeetCode/$dir" && mv "$dir" LeetCode/)
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name "leegyuho-programer"
          git config --global user.email "101032270+leegyuho-programer@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-move LeetCode problem folders to /LeetCode" || echo "No changes"
          git push
